CREATE TABLE `stds` (
  `stds_acc_id` int(11) NOT NULL AUTO_INCREMENT,
  `stds_email` varchar(255) NOT NULL,
  `stds_pass` varchar(255) NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `stds_std_num` varchar(12) DEFAULT NULL,
  `stds_lname` varchar(255) DEFAULT NULL,
  `stds_fname` varchar(255) DEFAULT NULL,
  `stds_mname` varchar(255) DEFAULT NULL,
  `stds_suffix` varchar(255) DEFAULT NULL,
  `stds_contact` varchar(255) DEFAULT NULL,
  `stds_gender` varchar(255) DEFAULT NULL,
  `stds_regligion` varchar(255) DEFAULT NULL,
  `stds_age` varchar(255) DEFAULT NULL,
  `stds_birth_month` varchar(255) DEFAULT NULL,
  `stds_birth_day` varchar(255) DEFAULT NULL,
  `stds_birth_year` varchar(255) DEFAULT NULL,
  `stds_address` longtext,
  `stds_profile_pic` longtext,
  `stds_account_theme` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`stds_acc_id`),
  UNIQUE KEY `stds_email` (`stds_email`),
  UNIQUE KEY `stds_std_num` (`stds_std_num`)
) ENGINE=InnoDB AUTO_INCREMENT=39390 DEFAULT CHARSET=latin1;

CREATE TABLE `stds_frm_addm` (
  `stds_submission_id` int(11) NOT NULL AUTO_INCREMENT,
  `stds_acc_id` int(11) DEFAULT NULL,
  `stds_status_bool` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `stds_birth_address` longtext,
  `stds_tel_number` varchar(255) DEFAULT NULL,
  `stds_grade_level` varchar(255) DEFAULT NULL,
  `stds_admission_strand` varchar(255) DEFAULT NULL,
  `stds_student_status` varchar(255) DEFAULT NULL,
  `stds_std_number` varchar(255) DEFAULT NULL,
  `stds_2x2_pic` longtext,
  `stds_psa` longtext,
  `stds_good_moral` longtext,
  `stds_form_137` longtext,
  `stds_std_lrn` varchar(255) DEFAULT NULL,
  `stds_former_school` longtext,
  `stds_former_graduate_year` varchar(255) DEFAULT NULL,
  `stds_former_school_year` varchar(255) DEFAULT NULL,
  `stds_mother_lname` varchar(255) DEFAULT NULL,
  `stds_mother_fname` varchar(255) DEFAULT NULL,
  `stds_mother_mname` varchar(255) DEFAULT NULL,
  `stds_mother_occupation` longtext,
  `stds_mother_contact` varchar(255) DEFAULT NULL,
  `stds_father_lname` varchar(255) DEFAULT NULL,
  `stds_father_fname` varchar(255) DEFAULT NULL,
  `stds_father_mname` varchar(255) DEFAULT NULL,
  `stds_father_occupation` longtext,
  `stds_father_contact` varchar(255) DEFAULT NULL,
  `stds_emergency_contact_lname` varchar(255) DEFAULT NULL,
  `stds_emergency_contact_fname` varchar(255) DEFAULT NULL,
  `stds_emergency_contact_mname` varchar(255) DEFAULT NULL,
  `stds_emergency_contact_contact` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`stds_submission_id`),
  UNIQUE KEY `stds_acc_id` (`stds_acc_id`),
  UNIQUE KEY `stds_std_number` (`stds_std_number`),
  UNIQUE KEY `stds_std_lrn` (`stds_std_lrn`),
  CONSTRAINT `stds_frm_addm_ibfk_1` FOREIGN KEY (`stds_acc_id`) REFERENCES `stds` (`stds_acc_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
